// internal/rbt/indexer.go
package rbt

import (
	"bufio"
	"crypto/sha256"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

type mapFileOutput struct {
	Mappings []mapOutputEntry `yaml:"mappings"`
}

type mapOutputEntry struct {
	Source     string   `yaml:"source"`
	Operations []string `yaml:"operations"`
}

// Indexer orchestrates map file generation from source code.
type Indexer struct {
	SrcDir    string
	SpecPath  string
	OutPath   string
	Overwrite bool
	Store     *IndexStore
	Embedder  Embedder
}

// RunRegex uses the regex parser to extract routes and writes caseforge-map.yaml.
func (idx *Indexer) RunRegex() error {
	if err := idx.checkOverwrite(); err != nil {
		return err
	}
	files, err := findSourceFiles(idx.SrcDir)
	if err != nil {
		return err
	}
	parser := NewRegexParser()
	mappings, err := parser.ExtractRoutes(idx.SrcDir, files)
	if err != nil {
		return err
	}
	return idx.writeMapFile(mappings, "regex")
}

// RunHybrid uses tree-sitter + embeddings + LLM confirmation.
func (idx *Indexer) RunHybrid(llmParser *LLMParser) error {
	if err := idx.checkOverwrite(); err != nil {
		return err
	}
	files, err := findSourceFiles(idx.SrcDir)
	if err != nil {
		return err
	}

	ts := NewTreeSitterParser()
	var mappings []RouteMapping
	if ts.IsAvailable() {
		mappings, err = ts.ExtractRoutes(idx.SrcDir, files)
		if err != nil {
			return err
		}
	}

	claimed := make(map[string]bool)
	for _, m := range mappings {
		claimed[m.SourceFile] = true
	}
	var unclaimed []ChangedFile
	for _, f := range files {
		if !claimed[f.Path] {
			unclaimed = append(unclaimed, f)
		}
	}

	if len(unclaimed) > 0 {
		if idx.Embedder != nil {
			if _, isNoop := idx.Embedder.(*NoopEmbedder); isNoop {
				regexMappings, _ := NewRegexParser().ExtractRoutes(idx.SrcDir, unclaimed)
				mappings = append(mappings, regexMappings...)
			} else {
				embedMappings, err := idx.runEmbedPhase(unclaimed)
				if err == nil {
					mappings = append(mappings, embedMappings...)
				}
			}
		}
	}

	return idx.writeMapFile(mappings, "hybrid")
}

func (idx *Indexer) runEmbedPhase(files []ChangedFile) ([]RouteMapping, error) {
	localIdx, err := idx.Store.Load()
	if err != nil || localIdx == nil {
		localIdx = &LocalIndex{}
	}
	for _, f := range files {
		data, err := os.ReadFile(f.Path)
		if err != nil {
			continue
		}
		hash := fmt.Sprintf("%x", sha256.Sum256(data))
		if !idx.Store.IsChunkStale(f.Path, hash) {
			continue
		}
		emb, err := idx.Embedder.Embed(string(data))
		if err != nil {
			continue
		}
		localIdx.Chunks = append(localIdx.Chunks, IndexChunk{
			File:      f.Path,
			Fn:        filepath.Base(f.Path),
			Hash:      hash,
			Embedding: emb,
		})
	}
	_ = idx.Store.Save(localIdx)
	return nil, nil
}

func (idx *Indexer) checkOverwrite() error {
	if _, err := os.Stat(idx.OutPath); err == nil && !idx.Overwrite {
		return fmt.Errorf("%s already exists; use --overwrite to replace it", idx.OutPath)
	}
	return nil
}

func (idx *Indexer) writeMapFile(mappings []RouteMapping, strategy string) error {
	byFile := make(map[string][]string)
	for _, m := range mappings {
		op := m.Method + " " + m.RoutePath
		byFile[m.SourceFile] = append(byFile[m.SourceFile], op)
	}

	var entries []mapOutputEntry
	for file, ops := range byFile {
		seen := make(map[string]bool)
		var deduped []string
		for _, op := range ops {
			if !seen[op] {
				seen[op] = true
				deduped = append(deduped, op)
			}
		}
		entries = append(entries, mapOutputEntry{Source: file, Operations: deduped})
	}
	for i := range entries {
		for j := i + 1; j < len(entries); j++ {
			if entries[i].Source > entries[j].Source {
				entries[i], entries[j] = entries[j], entries[i]
			}
		}
	}

	out := mapFileOutput{Mappings: entries}
	data, err := yaml.Marshal(out)
	if err != nil {
		return err
	}
	header := fmt.Sprintf("# caseforge-map.yaml — generated by `caseforge rbt index`\n"+
		"# Strategy: %s | Indexed: %s\n"+
		"# Review entries before committing.\n",
		strategy, time.Now().UTC().Format("2006-01-02T15:04:05Z"))
	return os.WriteFile(idx.OutPath, append([]byte(header), data...), 0644)
}

// findSourceFiles returns all supported source files under dir.
func findSourceFiles(dir string) ([]ChangedFile, error) {
	var files []ChangedFile
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		ext := strings.ToLower(filepath.Ext(path))
		if _, ok := langByExt[ext]; ok {
			files = append(files, ChangedFile{Path: path})
		}
		return nil
	})
	return files, err
}

// fileHash computes SHA256 hash of a file's content.
func fileHash(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", sha256.Sum256(data)), nil
}

// chunkFile splits a file into logical chunks (whole file for V1).
func chunkFile(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	lines := bufio.NewScanner(strings.NewReader(string(data)))
	var all strings.Builder
	for lines.Scan() {
		all.WriteString(lines.Text())
		all.WriteByte('\n')
	}
	return []string{all.String()}, nil
}
